name: Deploy to firebase

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      run: npm install
    - name: Test the code
      run: npm test
    - name: Deploy to Firebase
      uses: mohammed-atif/firebase-publish-react@v1.0
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
        build-application: true